### ISSUE TITLE
Finding app memory address

### ISSUE THREAD

**Issue by kvchen** [zku/SuperHaxagon#3]
Hey @zku, 

I was looking through your code, and the memory addresses for the game attribute offsets in your code don't seem to match up with the version of Super Hexagon I'm running (I'm not too sure which version I'm running, but I assume it's the latest).

I was wondering how you calculated the pointer to the rest of the app memory (the base pointer `0x694B00`) - and how I could calculate the offsets for other attributes (like the time, etc.) Any help would be much appreciated!

**Comment by zku** [comment]
I just re-downloaded the game (it has been a year), but it looks like the binary has not been changed; the offsets still match and the bot works.

MD5 of the superhexagon.exe binary: `c0e503aa1289e5ac50c428a4cf9e3c39` (from Windows Steam)

The developer used this engine for the Window creation and input handling: http://www.openframeworks.cc/ (you can see this by going through the RTTI / strings used in the binary). 

In the user-mode entry point main() function at `.text: 00439E30` the binary creates an ofAppGlutWindow instance and a superhex instance, and finally calls a function `.text: 004960B0` that initializes everything and runs the main loop of the game. 

During the initialization, it creates the object I called "base" (which is really a ofBaseApp instance), which contains all the relevant game data, and stores it in a global variable pointer at `0x694B00`: `.text:00496111 mov [0x694B00], edx`

As for the other data: if I remember correctly, I located the function responsible for playing a game sound ("gameover.wav") and then looked through the function that calls it to figure out the game-over conditions. That handler contains most of the game logic involving walls and player position. But it has been a while so I don't have any exact data on that anymore, sorry.

Hope that helps.

**Comment by zku** [comment]
I just checked again, the "PlayGameSound(int id)" function is at `0x439F50` and you can see a sample usage here:

```
0043D534   6A 04            PUSH 4 ; sound id
0043D536   8D8E E84F0200    LEA ECX,DWORD PTR DS:[ESI+24FE8]
0043D53C   E8 0FCAFFFF      CALL superhex.00439F50 ; play sound
```

The member function takes one argument: an integer for the sound id. ID=4 is the "you just crashed into a wall" sound, ID=1 plays "excellent!", and so on. There is a huge function at `.text: 0043CD40` which does most of the game-state checking and plays the appropriate sounds. Reversing that function is pretty straight forward and reveals most of the underlying structure required to extract the relevant game data.

**Comment by kvchen** [comment]
That trick about the game-over condition was super helpful, thanks! Got everything working now, much appreciated.

**Comment by kvchen** [comment]
Hate to bother you again like this, but I've got a couple more questions. I recently tried repeating the process of finding memory addresses but on Linux this time, since some of the tools I'm using in conjunction with the game are fairly Linux-specific. 

Since the binary format changed, all the memory addresses got shifted around - I did an `objdump` on the binary and tried looking through the output, but I wasn't able to locate the heap pointer or the game over function, as you suggested. I was wondering if you've got any tips on how to go about looking for these things in a systematic way - how were you able to resolve certain commands to their code counterparts (like the `main()` entrypoint, or the `ofAppGlutWindow` instance)?

Any help is super appreciated!

**Comment by zku** [comment]
Hey,

`objdump` is a really bad choice for analyzing large binaries, especially games. I'd recommend you use IDA Pro or Hopper (hopperapp). The Linux binary actually contains debug symbols as I just saw, so that would have made everything much easier (although I don't remember if Linux-Steam was already a thing back then).

If you can't use these tools, you can find main like this:

```
nm superhexagon.x86 | grep main
080550a0 T main
```

From the `main` function you can then find the `base` pointer at `0x085DFD5C`. Thanks to the symbols, we know that `PlaySound` is really `musicclass::playef` and the `GameLogic` function is really `superhex::gamelogic` at `0x080A4FC0`.

Since you already have some information from the Windows based analysis, it's quite simple to find the same things in the Linux binary using something like IDA Pro. For example, you can find strings referenced in the Windows binary and look for them in the Linux binary to figure out the corresponding function etc.

Good luck!

**Comment by kvchen** [comment]
I gave the trial for Hopper a shot, and it's pretty fantastic! I dug around a bit in the x64 binary for the `main` and `gamelogic` functions, and figured out these addresses:

```
POINTERS

* main: 0x410850
* ofRunApp(ofBaseApp*): 0x410a4c
* ofBaseAppPtr: 0xbae280

OFFSETS
* time: 0x28d0
* player angle: 0x28a0
* level (point, line, square, etc.): 0x28b0 or 0x28f0?
```

I figure a bit more digging around in the `gamelogic` function should be enough get the rest of them. I have a quick question about the walls - I'm assuming that the struct and loops for processing walls isn't as straightforward as the other addresses. Any tips for finding info in regards to those?

**Comment by zku** [comment]
Yep, these are a bit more tricky. You'll have to analyze the code and see how which values are being used, what they are being compared to etc.

For example, you'll find lots of references to 360.0 due to the circular nature of the game, and so on. This will help you identify what is what. In your case you don't have to analyze this from scratch. You can compare the Linux version to the Windows version and find similar code regions where the values are being used. If you see that wall distance is being compared to 150.0 in the Windows version, you can find the same comparison in the Linux version to figure out where the wall distance is kept. You may also assume that most of the structures are quite similar or even identical (except for compiler and architecture discrepancies due to alignment requirements etc.).

You could also attach `gdb` and manipulate the values you suspect of being responsible for something and then see how the change is reflected in the game.

There is not really one proper way of doing this, it just comes with time and patience, slowly analyzing the functions and data structures to figure out what they are.

I don't have too much time at the moment so I can't look up the offsets for you, but if you are struggling feel free to ask again. If I have some spare time I can look into it, but no promises.

**Comment by skorokithakis** [comment]
Hey guys, sorry for necroposting but I'm doing the exact same thing. I found the `main` offset in IDA, but I'm not quite sure how to go from that to the memory location of the value I want (in my case, background color). I'm assuming that I need to look for a `mov <register> <offset>` value and then take the offset from there, is that correct?

**Comment by zku** [comment]
That's hard to say. The way I would approach this is to read up on the documentation of the framework the game uses, specifically regarding how drawing works (e.g. how is a background generally drawn using this framework). Then I would try to identify the functions used and locate them in the game, find where they are being referenced and how they are being used. A very _very_ simplified example:

SomeGameEngine::RenderBackground(0xffff0000); // ARGB argument

Then it would be a matter of finding where this function is invoked (IDA can show you cross-references), and then changing the argument that is passed to the function.

I don't have the time at the moment to give you specific details for this game, I hope this helps.

**Comment by skorokithakis** [comment]
It does help, thank you. I figured out the broad strokes of how this thing goes last night while playing with IDA, hopefully I will be able to make some more progress with the method you describe. One problem I had was that I (think I) found the address of the gameclass `this` reference, but the memory offsets that should have contained values didn't, so I'm wondering whether I'm finding the base reference wrong (I found it by searching the memory for the level counter and then working backwards from the offsets in the code), or the specific offsets, or whether I'm doing something else wrong.

Another curious thing is that the level counter memory location changes whenever I run the game, while I would have expected the location to stay constant, is that not the case?

**Comment by zku** [comment]
What you are observing is called ASLR ( https://en.wikipedia.org/wiki/Address_space_layout_randomization ) affecting the heap and stack locations. The binary itself was compiled with a fixed base address, which explains the constant BasePointer = 0x694B00 which will remain the same for every execution. That memory location stores a pointer to the app object on the heap, which changes for every execution. Every other memory address of interest is relative to that value, computed using constant offsets to that value, as seen in the code.

**Comment by skorokithakis** [comment]
Ah, I thought it might have been that, but other commenters said it wasn't using ASLR on Linux. Too bad either way, thank you.
